spring.application.name=SurveyApp
spring.jpa.hibernate.ddl-auto = update
spring.datasource.url = jdbc:mysql://localhost:3306/capstone?createDatabaseIfNotExist=true
#spring.datasource.url = jdbc:mysql://database-2.c9wzzqrmu44l.us-east-1.rds.amazonaws.com/student?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = 1234
spring.datasource.diver-class-name =com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true
server. Port=9090

file.upload-dir=C:/uploads/images